### ISSUE TITLE
Gaussian processをdoubleにしている理由はなんですか？

### ISSUE THREAD

**Issue by MasanoriYamada** [naka-lab/HDP-GP-HSMM#1]
@nagano28 

こんにちは、

Gaussian processのところが動作が重いのでfloat32にしても問題ないと思うのですが、
doubleじゃないといけない理由はありますか？
https://github.com/naka-lab/HDP-GP-HSMM/blob/master/GaussianProcess.pyx#L78

**Comment by nagano28** [comment]
こんにちは

**Comment by nagano28** [comment]
@MasanoriYamada 

こんにちは，

GaussianProcess.pyxのdoubleをfloatに32にしても，動作はするかと思います．
きちんと検証はしていないので，今後してみます．

”gaussian processのところが重い”との事ですが，どのように計算時間を計測したか教えていただいてもよろしいでしょうか？
今後参考にさせていただきたいです．

計算の都合上で，Gaussian Process.pyxの関数を何度も呼び出していることが，時間がかかっている原因かと思います．
また，逆行列の計算もネックかと思います．

**Comment by MasanoriYamada** [comment]
@nagano28 
すいません、gaussian processが遅いのはちゃんと時間を測ったわけではなくdebuggerでstep実行しているときに時間がかかってるなと思っただけです。

それで中を見てみるとdoubleで扱ってるように見えたのでflaot32で扱って問題がないならfloat32にすれば単純に早くなると思ったからコメントしました😁

とりあえずfloat32にしても問題ないということ了解しました！

**Comment by nagano28** [comment]
@MasanoriYamada 

そうだったのですね．
確かにdoubleよりfloat32の方が早いですものね．
これまで精度重視で，あまり速度について取り組んでいなかったので大変助かります．

コメントありがとうございます！！
